# Generated by Django 3.0.3 on 2020-09-10 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default=None, max_length=50)),
                (
                    "job_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "landscape"),
                            (1, "trees"),
                            (2, "maintenance"),
                            (3, "annual odd job"),
                        ]
                    ),
                ),
                ("rate", models.PositiveSmallIntegerField(blank=True, default=1)),
                (
                    "property_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Commertial"), (1, "Residential")], default=0
                    ),
                ),
                (
                    "job_frequency",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "One-off job"), (1, "Recurring job")], default=0
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(null=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("visit_frequency", models.PositiveIntegerField(default=0, null=True)),
                ("duration", models.PositiveIntegerField(default=0, null=True)),
                (
                    "duration_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "days"),
                            (1, "weeks"),
                            (2, "months"),
                            (3, "years"),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
                ("address", models.TextField()),
                ("sign", models.CharField(max_length=50)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_task",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_task",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "tasks",},
        ),
        migrations.AddIndex(
            model_name="tasks",
            index=models.Index(fields=["user_id"], name="tasks_user_id_bd05b7_idx"),
        ),
    ]
