# Generated by Django 3.0.3 on 2020-09-10 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("create_bid", "0002_landscape"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandscapeFields",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=10)),
                ("total", models.FloatField()),
                (
                    "job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="create_bid.Landscape",
                    ),
                ),
            ],
            options={"db_table": "landscape_fields",},
        ),
        migrations.AddIndex(
            model_name="landscapefields",
            index=models.Index(
                fields=["job_id"], name="landscape_f_job_id__058fdb_idx"
            ),
        ),
    ]
